addi $r1, $zero, 1
addi $r2, $zero, 1
addi $r3, $zero, 1
addi $r4, $zero, 1
addi $r5, $zero, 1
addi $r6, $zero, 1
addi $r7, $zero, 1
addi $r8, $zero, 1
addi $r8, $r8, 1
addi $r8, $r8, 1
addi $r8, $r8, 1
addi $r8, $r8, 1
addi $r8, $r8, 1
addi $r8, $r8, 1
addi $r1, $zero, 1  #1     1
add $r1, $r1, $r1   #2     2
add $r1, $r1, $r1   #4     4
add $r1, $r1, $r1   #8     8
add $r1, $r1, $r1   #16    10
add $r1, $r1, $r1   #32    20
add $r1, $r1, $r1   #64    40
add $r1, $r1, $r1   #128   80
add $r1, $r1, $r1   #256   100
add $r1, $r1, $r1   #512   200
add $r1, $r1, $r1   #1024  400
add $r1, $r1, $r1   #2048  800
add $r1, $r1, $r1   #4096  1000
add $zero, $zero, $zero
add $zero, $zero, $zero
add $zero, $zero, $zero
add $zero, $zero, $zero
add $zero, $zero, $zero
